spring:
  datasource:
    name: yyy_db
    url: jdbc:mysql://rm-uf6f66d26gd6rl06io.mysql.rds.aliyuncs.com:3306/apple?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: apple
    password: apple
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update


#  rabbitmq:
#    host: 139.199.94.67
#    port: 5672
#    username: admin
#    password: admin
  redis:
    database: 0
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
    host: 139.199.94.67
  mail:
    host: mx1.qq.com
    username: 673713797@qq.com
    password: a18007154015
    default-encoding: utf-8
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 192.168.122.1:9300
      cluster-name: apple
#    port: 587
